1. Crie um array numpy com valores partindo de 10 até 49.

In [9]:
import numpy as np

array_valores = np.arange(10, 50)
print(array_valores)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Crie uma matriz numpy de 2 por 2 preenchida com 1's.

In [10]:
matriz_ones = np.ones((2, 2))
print(matriz_ones)

[[1. 1.]
 [1. 1.]]


3. Crie uma matriz numpy 3 por 2 de floats preenchida com 1's.

In [11]:
matriz_ones_float = np.ones((3, 2), dtype=float)
print(matriz_ones_float)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


4. Crie uma matriz 4 por 4 de integers preenchida com 5's.

In [12]:
matriz_cincos = np.full((4, 4), 5, dtype=int)
print(matriz_cincos)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


5. Crie uma matriz identidade de 3 por 3.

In [13]:
matriz_identidade = np.eye(3)
print(matriz_identidade)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


6. Crie um array numpy preenchido 3 integers aleatórias entre 1 e 10.

In [14]:
array_aleatorio = np.random.randint(1, 11, size=3)
print(array_aleatorio)

[5 6 7]


7. Dado o array X = np.array(['A','B','C','D','E']), mostre o último elemento.

In [31]:
X = np.array(['A', 'B', 'C', 'D', 'E'])
ultimo_elemento = X[-1]
print(ultimo_elemento)

E


8. Mostre os primeiros 3 elementos do array acima.

In [16]:
primeiros_elementos = X[:3]
print(primeiros_elementos)

['A' 'B' 'C']


9. Mostre só os elementos do meio do mesmo array acima.

In [32]:
elementos_do_meio = X[1:-1]
print(elementos_do_meio)

['B' 'C' 'D']


10. Inverta a ordem do array.

In [19]:
array_invertido = X[::-1]
print(array_invertido)

['E' 'D' 'C' 'B' 'A']


11. Mostre os elementos nas posições impar.

In [20]:
elementos_impares = X[1::2]
print(elementos_impares)

['B' 'D']


12. De acordo com a matriz, mostre a primeira linha Y = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
]).

In [34]:
Y = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
primeira_linha = Y[0, :]
print(primeira_linha)

[1 2 3 4]


13. Mostre o primeiro elemento na primeira linha.

In [35]:
primeiro_elemento = Y[0, 0]
print(primeiro_elemento)

1


14. Mostre a linha intermediária.

In [37]:
indice_linha_intermediaria = Y.shape[0] // 2
linha_intermediaria = Y[indice_linha_intermediaria, :]
print(linha_intermediaria)

[ 9 10 11 12]


15. Os primeiros 2 elementos das duas primeiras linhas.

In [38]:
elementos = Y[:2, :2]
print(elementos)

[[1 2]
 [5 6]]


16. Os últimos 2 elementos das duas últimas linhas.

In [39]:
elementos = Y[-2:, -2:]
print(elementos)

[[11 12]
 [15 16]]


17. De acordo com o array Z = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4]), faça a soma.





In [40]:
Z = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
soma = np.sum(Z)
print(soma)

43


18. Faça a média do array acima.

In [41]:
media = np.mean(Z)
print(media)

4.777777777777778


19. Dada a matriz faça a soma das colunas W = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
]).

In [42]:
W = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
soma_colunas = np.sum(W, axis=0)
print(soma_colunas)


[28 32 36 40]


20. Faça a média das linhas.

In [43]:
media_linhas = np.mean(W, axis=1)
print(media_linhas)

[ 2.5  6.5 10.5 14.5]


21. Dado o array H = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10]), mostre o elemento de maior valor.

In [44]:
H = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
maior_valor = np.max(H)
print(maior_valor)

10
